CLM10       UNCAS TRANSFORM, CHARACTER INTO NONE CHARACTER VECTOR.
C
      SUBROUTINE LM10 (R,C,N)
C
      CHARACTER C*4
      DIMENSION R(1),C(1)
C
    1 FORMAT(A4)
C
C
      DO 100 I=1,N
  100 READ(C(I),1) R(I)

C
      RETURN
      END
