CLM3A        LINEARIZATION
C
      SUBROUTINE LM3A (CENT,DELTA1,DEPSI,F,F0,G,NG,G0,K,KL,LIN,N,PCONT,
     &                 PP,START,X0,TD,XX,G1,G2,AMAX,ERRM,NF,X,FUNK,
     &                 INDEX,XREL,GREL,G3,K1,NVAR,IUT3,IRET1)
C
      DIMENSION X0(1),XX(1),G0(1),G1(1),G2(1),G(NG,1),F(1),
     &          AMAX(1),CENT(1),X(1),INDEX(1),XREL(1),
     &          GREL(1),G3(1)
      INTEGER PP,PCONT
      LOGICAL CENT,CONT,LIN,START
      EXTERNAL FUNK
      print *,'you are in LM3A'
C
C
      DO 10 NN=1,N
      XX(NN)=X0(NN)
   10 CONTINUE
C
      IF(.NOT.START)GOTO 40
C
C.... CALCULATION
      CALL LM9A (XX,F0,G0,N,NF,X,FUNK,INDEX,XREL,GREL,G3,K1,
     &           NVAR,IUT3,IRET1)
      IF (IRET1 .EQ. 1) GOTO 145
      IF(KL.LE.0)GOTO 35
C
      DELTA2=DELTA1*10.
      DO 30 NN=1,N
      XX(NN)=X0(NN)+DELTA2
C.... CALCULATION
      CALL LM9A (XX,F2,G2,N,NF,X,FUNK,INDEX,XREL,GREL,G3,K1,
     &           NVAR,IUT3,IRET1)
      IF (IRET1 .EQ. 1) GOTO 145
      XX(NN)=X0(NN)
      IF(.NOT.LIN)GOTO 25
      F(NN)=(F2-F0)/DELTA2
C
   25 DO 20 KK=1,KL
      G(KK,NN)=(G2(KK)-G0(KK))/DELTA2
   20 CONTINUE
   30 CONTINUE
C
   35 PP=0
      DO 37 NN=1,N
   37 CENT(NN)=.TRUE.
      CONT=.TRUE.
      GOTO 60
   40 PP=PP+1
      IF(PP.LT.PCONT)GOTO 50
C
      PP=0
      CONT=.TRUE.
      GOTO 60
C
   50 CONT=.FALSE.
C
   60 CONTINUE
C
      DO 90 NN=1,N
      IF(CONT)GOTO 75
      IF(.NOT.CENT(NN))GOTO 85

C.... CENTRAL DIFFERENCES
   75 CONTINUE
      XX(NN)=XX(NN)-DELTA1/2.0
C.... CALCULATION
      CALL LM9A (XX,F1,G1,N,NF,X,FUNK,INDEX,XREL,GREL,G3,K1,
     &           NVAR,IUT3,IRET1)
      IF (IRET1 .EQ. 1) GOTO 145
C
      XX(NN)=XX(NN)+DELTA1
C.... CALCULATION
      CALL LM9A (XX,F2,G2,N,NF,X,FUNK,INDEX,XREL,GREL,G3,K1,
     &           NVAR,IUT3,IRET1)
      IF (IRET1 .EQ. 1) GOTO 145
      XX(NN)=X0(NN)
      print *,F2,'F222'
      IF(.NOT.LIN)F(NN)=(F2-F1)/DELTA1
C
      IF(ERRM.EQ.0.) GOTO 76
      YERROR= AMAX1(ABS(F0-0.5*(F1+F2)),1.E-20)
      AMAX(NN)=DELTA1*SQRT(ERRM*(AMAX1(ABS(F0),ABS(AMAX(NN)*F(NN)))+
     & TD)/YERROR)
      AMXF=AMAX(NN)
      AMXG=1.E30
   76 CONTINUE

      KJ=KL+1
      IF(KJ.GT.K)GOTO 90
      DO 80 KK=KJ,K
      G(KK,NN)=(G2(KK)-G1(KK))/DELTA1

      IF(ERRM.EQ.0.) GOTO 80
      YERROR= AMAX1(ABS(G0(KK)-0.5*(G1(KK)+G2(KK))),1.E-20)
      AMM=DELTA1*SQRT(ERRM*(AMAX1(ABS(G0(KK)),ABS(AMAX(NN)*G(KK,NN)))+
     & TD)/YERROR)
      AMXG=AMIN1(AMXG,AMM)
   80 CONTINUE
      IF(ERRM.NE.0.) AMAX(NN)=AMIN1(AMXF,AMXG)
      GOTO 90

C.... SIMPLE DIFFERENCES
   85 XX(NN)=XX(NN)+DELTA1
C.... CALCULATION
      CALL LM9A (XX,F2,G2,N,NF,X,FUNK,INDEX,XREL,GREL,G3,K1,
     &           NVAR,IUT3,IRET1)
      IF (IRET1 .EQ. 1) GOTO 145
      XX(NN)=X0(NN)
      IF(.NOT.LIN)F(NN)=(F2-F0)/DELTA1
      KJ=KL+1
      IF(KJ.GT.K)GOTO 90
      DO 87 KK=KJ,K
      G(KK,NN)=(G2(KK)-G0(KK))/DELTA1
   87 CONTINUE

   90 CONTINUE
C
      IF(.NOT.CONT)GOTO 130
C
      DO 120 NN=1,N
      CENT(NN)=.TRUE.
      XX(NN)=X0(NN)+DELTA1
C.... CALCULATION
      CALL LM9A (XX,F1,G1,N,NF,X,FUNK,INDEX,XREL,GREL,G3,K1,
     &           NVAR,IUT3,IRET1)
      IF (IRET1 .EQ. 1) GOTO 145
      XX(NN)=X0(NN)
      IF(LIN)GOTO 100
C
      IF((ABS(F(NN)-(F1-F0)/DELTA1)).GT.(ABS(F(NN))*DEPSI+TD))GOTO 120
C
  100 IF(KJ.GT.K)GOTO 115
      DO 110 KK=KJ,K
      IF((ABS(G(KK,NN)-(G1(KK)-G0(KK))/DELTA1)).GT.
     & (DEPSI*AMAX1(ABS(G0(KK)/AMAX(NN)),ABS(G(KK,NN)))+TD))GOTO 120
  110 CONTINUE
  115 CONTINUE
      CENT(NN)=.FALSE.
  120 CONTINUE
C
C
  130 CONTINUE
  145 print *,"end of LM3A"
      RETURN
      END
