CLM6        AGAIN
C
      SUBROUTINE LM6 (N,ALFA,AM,SCALAR,SIGNAL,NP,SIGLIM,K,NN)
      DIMENSION AM(1),SIGNAL(NP,2)
      INTEGER   SIGNAL,SIGLIM
C
C
      IF(SIGNAL(NN,K).LT.SIGLIM)GOTO 10
      IF(ABS(SCALAR).LT.(0.99*AM(NN)))GOTO 10
C
      SIGNAL(NN,K)=1
      AM(NN)=AM(NN)*ALFA
      GOTO 20
C
   10 SIGNAL(NN,K)=SIGNAL(NN,K)+1
C
   20 RETURN
      END
