PROCSTART 
PARAM     X
PARAM     &SCROLL
CALL      CIFNEQ    2         33
PARAM     ?
PARAM     &BOOSMA
CALL      CIFEQ     2         2
ASSGN     .MSG      OPTRM155
PARAM     ?
PARAM     &BOOSVO
CALL      CIFEQ     2         2
ASSGN     .MSG      OPTRM156
PARAM     ?
PARAM     &BOOSRE
CALL      CIFEQ     2         2
ASSGN     .MSG      OPTRM157
PARAM     ?
PARAM     &BOOSTR
CALL      CIFEQ     2         2
ASSGN     .MSG      OPTRM158
MSGPARAM  OPTRM155
NBPARAM   NO
PARAM     &BOOSMA
CALL      CVR       3
MSGPARAM  OPTRM156
NBPARAM   NO
PARAM     &BOOSVO
CALL      CVR       3
MSGPARAM  OPTRM157
NBPARAM   NO
PARAM     &BOOSRE
CALL      CVR       3
MSGPARAM  OPTRM158
NBPARAM   NO
PARAM     &BOOSTR
CALL      CVR       3
PROCEND   
